name: Deploy Official Web Rtravel
on:
  push:
    branches:
      [deploy]

jobs:
  Deploy-in-prod:
    runs-on: ubuntu-latest
    environment: deploy
    steps:
      - name: executing remote ssh commands using ssh key
        uses: ./
        with:
            host: ${{ secret.SSH_SECRET_HOST }}
            username: ${{ secret.SSH_SECRET_USERNAME }}
            key: ${{ secret.SSH_SECRET_HOST }}
            script: |
              cd revolutiontravelagency.com/
              git pull origin deploy &&  php composer.phar install && php artisan config:cache && php artisan config:clear && php artisan cache:clear && npm install && npm run build
              
              

