name: Deploy Official Web Rtravel
on:
  push:
    branches:
      [deploy]

jobs:
  Deploy-in-prod:
    runs-on: ubuntu-latest
    steps:
      - run: ssh dh_dyq4tc@achebe.dreamhost.com
      - run: Pilo*2023
      - run: cd revolutiontravelagency.com/
      - run: git pull origin deploy &&  php composer.phar install && php artisan config:cache && php artisan config:clear && php artisan cache:clear && npm install && npm run build



